/**
 * Shared SEO keywords for all pages. Helps search engines understand the site's topic.
 */
export const seoKeywords = [
  "app scheduler",
  "app scheduler for android",
  "auto open apps",
  "automatic app launcher",
  "productivity android app",
  "schedule apps android",
  "google play app scheduler",
  "app scheduler google play",
  "task scheduling app",
  "app automation",
  "open apps automatically",
  "workflow automation",
  "productivity app",
  "android app scheduler",
  "app launch automation",
  "time-based app launcher",
  "automatic app opener",
  "schedule apps automatically",
  "app opening scheduler",
  "calendar workflow automation",
  "meeting reminder app",
  "workflow planner",
  "automatic app scheduler",
  "productivity tools",
  "app reminder",
  "task automation",
  "Appopener",
];
